### ISSUE TITLE
Unclear instructions on how to install locally

### ISSUE THREAD

**Issue by Gamanpost** [requinDr/tsukiweb-public#13]
Hello! This project looks to be fantastic, and I'd like to install it locally, but since I basically have no coding knowledge, the current instructions for how to do so feel quite unclear to me. Basically I installed node.js, i ran `npm i`  and it simply said `up to date, audited 49 packages in (time)`, but when I run `npm start` it  just reads `Missing script: "start"`. I probably have skipped a lot of steps very obvious to some, but for the life of me I cannot figure out what to do after having installed node.js. Anyways, thanks for the project!

**Comment by requinDr** [comment]
Hello. I admit that the instructions are more aimed to potentials developpers.
The game won't entirely run locally too, the assets (audio, images and scenes) aren't here.
It means that while the code run on your PC, it stil need an internet connection to pull them.

If you still wan't to run it, here are some instructions, a bit more detailed I hope.

1) Download the project (the green button on the `<> Code` tab)
![Capture d'écran 2024-07-13 094754](https://github.com/user-attachments/assets/0105bb47-d5cf-45e6-a567-6f7374826da6)

2) Extract .zip

3) Go to the extracted location, and write `cmd` in the path bar.
It will open the cmd at your current location.
![screen-tsukiweb](https://github.com/user-attachments/assets/953bfdb5-1920-4f0b-92f9-fe4e3fed041b)

4) Write `npm i`

5) Write `npm start`


If you still run into the same error, check that you have the `package.json` at the root of the project and that the following lines are present in it:
```json
  "scripts": {
    "start": "vite",
    "build": "tsc && vite build"
  },
```

**Comment by Gamanpost** [comment]
Wow thank you very much!
