### ISSUE TITLE
Add Command To Install Submodules in README.md

### ISSUE THREAD

**Issue by ashmanix** [requinDr/tsukiweb-public#18]
As the repo now has a submodule in it for `tsukiweb-common` I have a suggestion to add to the README to run the command `git submodule update --init --recursive` for anyone who had cloned the repo previously before it had a submodule, to then add it. Or use `git clone --recursive` or whatever the relevant command is when first cloning the repo.

It was just something that caught me off guard.

**Note: Thanks a lot for making this available!**

**Comment by requinDr** [comment]
You are right. I added the instruction for a first time cloning. Thanks for the suggestion!
I'm leaving the upgrade process to the user. Either they know, search or clone again.
