### ISSUE TITLE
Using correct font to display Japanese characters in Chrome-based browsers

### ISSUE THREAD

**Issue by feored** [requinDr/tsukiweb-public#4]
Hello,

I'm trying to read Tsukihime again in Japanese as a learning opportunity and I've noticed that on chrome-based browsers, the kanji aren't displayed correctly by default.

[Here's an example from early on in the game](https://files.catbox.moe/ye1kmp.png), where the kanji 空 is displayed with either "straight" or "bent" legs depending on your default font. This seems to be caused by [Han unification](https://en.wikipedia.org/wiki/Han_unification), where the same unicode character is used for Chinese, Japanese and Korean languages.

From my testing, this happens on Vivaldi and Chrome, but not Firefox and Edge. I've tried switching between Japanese and English locales on my computer with no effect, so I'm guessing some browsers simply default to Chinese and others Japanese to display these characters. 

It's not a huge deal as it can be fixed by forcing a Japanese font in your browser (i.e MS PGothic), but adding lang="ja" instead of lang="en" in the HTML also seems to make Chrome default to the correct font, so that's the fix I'm suggesting.

PS: Bravo les gars, ce projet est vraiment génial !

**Comment by loicfrance** [comment]
Thanks for pointing this very specific issue, and for the solution. I'll make sure the locale is updated according to the chosen language.
