### ISSUE TITLE
Mixed up CGs for Arc's endings

### ISSUE THREAD

**Issue by Sakimotor** [requinDr/tsukiweb-public#5]
In the endings preview, the CGs for Tsukihime (true end) and Moon at Dawn (good end) seem mixed up
![firefox_7XB6iW9LLd](https://github.com/requinDr/tsukiweb-public/assets/20578016/35e75a5e-79c3-4fa1-8f90-de04464890d4)

**Comment by requinDr** [comment]
Fixed in 5452f9396305fc6fef2a5e5bf60683c069f91b29, thanks for the report. It will be part of the next release
