### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by shiki-tm** [requinDr/tsukiweb-public#8]
I'd love to read tsukihime in chinese! how hard is it to add a language? 

Please let me know what you need me to do to get this added. I have the files. 

Any help is appreciated

**Comment by requinDr** [comment]
Not hard at all!
I wen't into details [here](https://github.com/requinDr/tsukiweb-public/wiki/Adding-translation)

You can take the recent example of what was done to add Spanish as a reference https://github.com/requinDr/tsukiweb-public/commit/54b3994ba7e5b9e2109f6cfd706320ec03deed63

**Comment by shiki-tm** [comment]
thanks for the link, im trying to use the script converter but getting errors. also the script txt file is originally in GB 2312 encoding but if i change it to utf8 it turns into some gibberish. is that okay for the convert script? Is it possible you could help me with running the script conversion? if possible is there a way to contact you more easily? thanks again

**Comment by requinDr** [comment]
You don't need to actually convert it. See the commit for Spanish and [What files should be included in your PR](https://github.com/requinDr/tsukiweb-public/wiki/Adding-translation#what-files-should-be-included-in-your-pr).

**Comment by requinDr** [comment]
For future refrence, anyone may refer to PR #9 and #10 , closing this issue.
Thanks for your contribution @shiki-tm !
